// api/videoStream.ts — v16 (Service Worker signature protection)
//
// IDM PREVENTION — FINAL CORRECT SOLUTION:
//
// ARCHITECTURE:
//   action=play  → native Range streaming (instant start, real seeking)
//                  requires X-Video-Time + X-Video-Sig headers on EVERY request
//                  generated by the Service Worker running in the page context
//                  IDM bypasses the SW → no headers → 403
//
//   action=chunk → sequential token-chain chunks (fallback if SW unavailable)
//   action=meta  → returns playToken + swSecret (derived from playToken)
//   action=info  → total size / chunk count
//
// SIGNATURE SCHEME:
//   swSecret  = HMAC(TOKEN_SECRET, "sw-v1:" + playToken) — derived, never stored
//   X-Video-Sig = HMAC(swSecret, "${timestamp}:${rangeHeader}:${videoId}")
//   X-Video-Time = Unix ms timestamp (must be within 30s of server time)
//   Signature is Range-bound → captured sig cannot be used for other byte ranges
//
// TOKEN EXPIRY: playToken = 2 hours, chunkToken = 5 min, streamToken = 5 min

import type { VercelRequest, VercelResponse } from '@vercel/node';
import crypto from 'crypto';
import admin from 'firebase-admin';

const CONFIG = {
  MASTER_SECURITY_STRING: process.env.VIDEO_SECURITY_STRING || 'CHANGE_ME',
  TOKEN_SECRET:           process.env.VIDEO_TOKEN_SECRET    || 'CHANGE_ME',
  CHUNK_SIZE:             1 * 1024 * 1024,
  ALLOWED_ORIGIN:         process.env.VIDEO_ALLOWED_ORIGIN  || '*',
  SIG_WINDOW_MS:          30_000,  // signature valid for 30 seconds
};

// ─── Firebase Admin ──────────────────────────────────────────────────────────────
let _db: admin.firestore.Firestore | null = null;
function getDb(): admin.firestore.Firestore {
  if (_db) return _db;
  if (!admin.apps.length) {
    const projectId   = process.env.FIREBASE_PROJECT_ID;
    const clientEmail = process.env.FIREBASE_CLIENT_EMAIL;
    let   privateKey  = process.env.FIREBASE_PRIVATE_KEY;
    if (!projectId || !clientEmail || !privateKey) throw new Error('Missing Firebase credentials');
    privateKey = privateKey.trim().replace(/^["']|["']$/g, '').replace(/\\n/g, '\n');
    admin.initializeApp({ credential: admin.credential.cert({ projectId, clientEmail, privateKey }) });
  }
  _db = admin.app().firestore();
  return _db;
}

// ─── In-memory Firestore cache (2h TTL) ─────────────────────────────────────────
interface VidEntry { streamUrl: string; isGoogleDrive: boolean; isEmbed: boolean; platform: string; cachedAt: number; }
const _cache = new Map<string, VidEntry>();
async function getVid(videoId: string): Promise<VidEntry | null> {
  const hit = _cache.get(videoId);
  if (hit && Date.now() - hit.cachedAt < 2 * 3600_000) return hit;
  const snap = await getDb().collection('securedVideos').doc(videoId).get();
  if (!snap.exists) return null;
  const d = snap.data()!;
  const entry: VidEntry = { streamUrl: d.streamUrl, isGoogleDrive: d.isGoogleDrive || false, isEmbed: d.isEmbed || false, platform: d.platform, cachedAt: Date.now() };
  _cache.set(videoId, entry);
  return entry;
}

// ─── CORS ────────────────────────────────────────────────────────────────────────
function cors(req: VercelRequest, res: VercelResponse) {
  const origin  = req.headers.origin as string | undefined;
  const allowed = CONFIG.ALLOWED_ORIGIN;
  if (allowed === '*' || (origin && (allowed === origin || allowed.split(',').map(s => s.trim()).includes(origin))))
    res.setHeader('Access-Control-Allow-Origin', origin || '*');
  else res.setHeader('Access-Control-Allow-Origin', allowed);
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers',
    'Content-Type, X-Security-String, X-Stream-Token, X-Chunk-Token, ' +
    'Authorization, Accept, Origin, X-Requested-With, Range, ' +
    'X-Video-Time, X-Video-Sig');
  res.setHeader('Access-Control-Expose-Headers',
    'X-Next-Chunk-Token, X-Chunk-Index, X-Is-Last-Chunk, Content-Range, Content-Length, Accept-Ranges');
  res.setHeader('Access-Control-Max-Age', '86400');
}

// ─── Crypto helpers ──────────────────────────────────────────────────────────────
function hmac(key: string, data: string): string {
  return crypto.createHmac('sha256', key).update(data).digest('hex');
}
function safeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  try { return crypto.timingSafeEqual(Buffer.from(a, 'hex'), Buffer.from(b, 'hex')); }
  catch { return false; }
}

// ─── Tokens ──────────────────────────────────────────────────────────────────────
function makeToken(payload: string): string {
  return Buffer.from(`${payload}:${hmac(CONFIG.TOKEN_SECRET, payload)}`).toString('base64url');
}
function checkToken(token: string, prefix: string, fields: string[]): string[] | null {
  try {
    const decoded = Buffer.from(token, 'base64url').toString('utf8');
    const parts   = decoded.split(':');
    const nFields = fields.length;
    if (parts.length !== nFields + 2) return null;              // prefix + fields + expiry + sig
    if (parts[0] !== prefix) return null;
    const expiry = parseInt(parts[nFields], 10);
    if (Date.now() > expiry) return null;
    const payload  = parts.slice(0, nFields + 1).join(':');
    const expected = hmac(CONFIG.TOKEN_SECRET, payload);
    if (!safeEqual(parts[nFields + 1], expected)) return null;
    return parts.slice(1, nFields);                             // return field values
  } catch { return null; }
}

// play token — 2 hours
function makePlayToken(videoId: string): string {
  return makeToken(`play:${videoId}:${Date.now() + 7_200_000}`);
}
function checkPlayToken(token: string, videoId: string): boolean {
  const f = checkToken(token, 'play', ['vid', 'exp']);
  return f !== null && f[0] === videoId;
}

// stream token — 5 min (for action=info)
function makeStreamToken(videoId: string): string {
  return makeToken(`stream:${videoId}:${Date.now() + 300_000}`);
}
function checkStreamToken(token: string, videoId: string): boolean {
  const f = checkToken(token, 'stream', ['vid', 'exp']);
  return f !== null && f[0] === videoId;
}

// chunk token — 5 min, index-bound
function makeChunkToken(videoId: string, idx: number): string {
  return makeToken(`chunk:${videoId}:${idx}:${Date.now() + 300_000}`);
}
function checkChunkToken(token: string, videoId: string, idx: number): boolean {
  const f = checkToken(token, 'chunk', ['vid', 'idx', 'exp']);
  return f !== null && f[0] === videoId && parseInt(f[1], 10) === idx;
}

// SW secret — derived from play token, never stored server-side
// swSecret = HMAC(TOKEN_SECRET, "sw-v1:" + playToken)
function deriveSwSecret(playToken: string): string {
  return hmac(CONFIG.TOKEN_SECRET, 'sw-v1:' + playToken).substring(0, 32);
}

// ─── SW signature validation ─────────────────────────────────────────────────────
function checkSwSig(req: VercelRequest, videoId: string, playToken: string): string | null {
  const timeStr = req.headers['x-video-time'] as string | undefined;
  const sig     = req.headers['x-video-sig']  as string | undefined;
  if (!timeStr || !sig) return 'missing signature headers';
  const ts = parseInt(timeStr, 10);
  if (isNaN(ts) || Math.abs(Date.now() - ts) > CONFIG.SIG_WINDOW_MS) return 'signature expired';
  const range    = (req.headers['range'] || '') as string;
  const secret   = deriveSwSecret(playToken);
  const expected = hmac(secret, `${ts}:${range}:${videoId}`);
  if (!safeEqual(sig, expected)) return 'invalid signature';
  return null; // OK
}

// ─── UA blocklist ────────────────────────────────────────────────────────────────
function badUA(req: VercelRequest): boolean {
  const ua = (req.headers['user-agent'] || '').toLowerCase();
  return ['idm/', 'internet download manager', 'fdm/', 'free download manager',
    'wget/', 'curl/', 'aria2', 'uget', 'getright', 'flashget', 'dap/',
    'download accelerator', 'go-http-client', 'python-requests', 'libwww-perl',
    'java/', 'okhttp/', 'jdownloader', 'motrix', 'xdm/', 'axel/',
    'yt-dlp', 'youtube-dl', '4kdownload', 'httrack',
  ].some(b => ua.includes(b));
}
function badReferer(req: VercelRequest): boolean {
  const ref = (req.headers['referer'] || req.headers['origin'] || '') as string;
  if (!ref) return false;
  const allowed = CONFIG.ALLOWED_ORIGIN === '*' ? [] : CONFIG.ALLOWED_ORIGIN.split(',').map(s => s.trim());
  if (allowed.length === 0) return false;
  return !allowed.some(o => ref.startsWith(o));
}

// ─── URL converters ──────────────────────────────────────────────────────────────
type CR = { ok: true; url: string; embed: boolean; gdrive?: boolean } | { ok: false; msg: string };
function dropbox(url: string): CR {
  try {
    let u = url;
    if (!u.includes('raw=1')) {
      if (u.includes('dl=0')) u = u.replace('dl=0', 'raw=1');
      else if (u.includes('dl=1')) u = u.replace('dl=1', 'raw=1');
      else u += (u.includes('?') ? '&' : '?') + 'raw=1';
    }
    return { ok: true, url: u, embed: false };
  } catch (e: any) { return { ok: false, msg: e.message }; }
}
function gdrive(url: string): CR {
  try {
    const m = url.match(/\/file\/d\/([^/?]+)/) || url.match(/[?&]id=([^&]+)/);
    if (m) return { ok: true, url: `https://drive.google.com/uc?export=download&id=${m[1]}&confirm=t`, embed: false, gdrive: true };
    return { ok: false, msg: 'Invalid Google Drive URL' };
  } catch (e: any) { return { ok: false, msg: e.message }; }
}
function youtube(url: string): CR {
  try {
    const u = new URL(url), v = u.hostname.includes('youtu.be') ? u.pathname.slice(1) : u.searchParams.get('v');
    if (v) return { ok: true, url: `https://www.youtube.com/embed/${v}`, embed: true };
    return { ok: false, msg: 'Invalid YouTube URL' };
  } catch (e: any) { return { ok: false, msg: e.message }; }
}
function vimeo(url: string): CR {
  try {
    const u = new URL(url), v = u.pathname.split('/').filter(Boolean)[0];
    if (v) return { ok: true, url: `https://player.vimeo.com/video/${v}`, embed: true };
    return { ok: false, msg: 'Invalid Vimeo URL' };
  } catch (e: any) { return { ok: false, msg: e.message }; }
}
function dailymotion(url: string): CR {
  try {
    const u = new URL(url), v = u.pathname.split('/').filter(p => p && p !== 'video')[0];
    if (v) return { ok: true, url: `https://www.dailymotion.com/embed/video/${v}`, embed: true };
    return { ok: false, msg: 'Invalid Dailymotion URL' };
  } catch (e: any) { return { ok: false, msg: e.message }; }
}
const converters: Record<string, (u: string) => CR> = { dropbox, gdrive, youtube, vimeo, dailymotion };

// ─── Handlers ────────────────────────────────────────────────────────────────────

async function handleSubmit(req: VercelRequest, res: VercelResponse) {
  const { sourceUrl, platform, label, createdBy } = req.body || {};
  if (!sourceUrl || !platform || !createdBy) return res.status(400).json({ success: false, message: 'sourceUrl, platform, createdBy required' });
  const conv = converters[String(platform).toLowerCase()];
  if (!conv) return res.status(400).json({ success: false, message: `Unsupported platform: ${platform}` });
  const result = conv(String(sourceUrl));
  if (!result.ok) return res.status(400).json({ success: false, message: result.msg });
  const docRef = await getDb().collection('securedVideos').add({
    originalUrl: sourceUrl, streamUrl: result.url,
    platform: String(platform).toLowerCase(), isEmbed: result.embed,
    isGoogleDrive: (result as any).gdrive || false,
    label: label || '', createdBy: String(createdBy),
    createdAt: new Date().toISOString(), accessCount: 0,
  });
  return res.status(200).json({ success: true, proxyUrl: `secured://${docRef.id}`, videoId: docRef.id });
}

async function handleMeta(req: VercelRequest, res: VercelResponse) {
  const videoId = String(req.query.videoId || '');
  const secKey  = req.headers['x-security-string'] as string | undefined;
  if (!secKey || secKey.trim() !== CONFIG.MASTER_SECURITY_STRING.trim())
    return res.status(403).json({ success: false, message: 'Forbidden' });
  if (!videoId) return res.status(400).json({ success: false, message: 'videoId required' });

  const db   = getDb();
  const snap = await db.collection('securedVideos').doc(videoId).get();
  if (!snap.exists) return res.status(404).json({ success: false, message: 'Video not found' });
  const d = snap.data()!;
  _cache.set(videoId, { streamUrl: d.streamUrl, isGoogleDrive: d.isGoogleDrive || false, isEmbed: d.isEmbed || false, platform: d.platform, cachedAt: Date.now() });
  db.collection('securedVideos').doc(videoId).update({ accessCount: (d.accessCount || 0) + 1, lastAccessedAt: new Date().toISOString() }).catch(() => {});

  if (d.isEmbed) return res.status(200).json({ success: true, type: 'embed', embedUrl: d.streamUrl, platform: d.platform });

  const playToken   = makePlayToken(videoId);
  const swSecret    = deriveSwSecret(playToken);   // sent to SW, used to sign Range requests
  const streamToken = makeStreamToken(videoId);
  const firstChunk  = makeChunkToken(videoId, 0);  // fallback chunk chain

  return res.status(200).json({
    success: true, type: 'video',
    playToken, swSecret, streamToken,
    firstChunkToken: firstChunk,
    platform: d.platform,
  });
}

async function handleInfo(req: VercelRequest, res: VercelResponse) {
  const videoId = String(req.query.videoId || '');
  const token   = (req.headers['x-stream-token'] || req.query.token) as string | undefined;
  if (!token || !checkStreamToken(token, videoId)) return res.status(403).json({ success: false, message: 'Forbidden' });
  if (badUA(req)) return res.status(403).json({ success: false, message: 'Forbidden' });
  const vid = await getVid(videoId);
  if (!vid) return res.status(404).json({ success: false, message: 'Not found' });
  const headers: Record<string, string> = { 'User-Agent': 'Mozilla/5.0' };
  if (vid.isGoogleDrive) headers['Referer'] = 'https://drive.google.com/';
  const { default: fetch } = await import('node-fetch');
  const r         = await (fetch as any)(vid.streamUrl, { method: 'HEAD', headers, redirect: 'follow' });
  const totalSize = parseInt(r.headers.get('content-length') || '0', 10);
  return res.status(200).json({ success: true, totalSize, totalChunks: totalSize > 0 ? Math.ceil(totalSize / CONFIG.CHUNK_SIZE) : null, chunkSize: CONFIG.CHUNK_SIZE });
}

// ─── handlePlay — SW-signature-protected native Range streaming ──────────────────
//
// For the browser: SW intercepts Range request → adds HMAC sig → passes here → validates → streams.
// For IDM: makes its own request without SW → no sig headers → 403.
//
async function handlePlay(req: VercelRequest, res: VercelResponse) {
  const videoId = String(req.query.videoId || '');
  const token   = String(req.query.token   || '');

  if (!checkPlayToken(token, videoId)) return res.status(403).send('Forbidden: invalid token');
  if (badUA(req))                      return res.status(403).send('Forbidden: blocked client');
  if (badReferer(req))                 return res.status(403).send('Forbidden: invalid origin');

  // SW signature — this is the actual IDM block
  const sigErr = checkSwSig(req, videoId, token);
  if (sigErr) return res.status(403).send(`Forbidden: ${sigErr}`);

  const vid = await getVid(videoId);
  if (!vid) return res.status(404).send('Not found');

  const range = req.headers['range'] as string | undefined;
  const upHeaders: Record<string, string> = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    Accept: '*/*',
    Connection: 'keep-alive',
  };
  if (range)            upHeaders['Range']   = range;
  if (vid.isGoogleDrive) upHeaders['Referer'] = 'https://drive.google.com/';

  const { default: fetch } = await import('node-fetch');
  let upstream: any;
  try {
    upstream = await (fetch as any)(vid.streamUrl, { headers: upHeaders, redirect: 'follow', compress: false });
  } catch { return res.status(502).send('Upstream error'); }

  if (!upstream.ok && upstream.status !== 206) return res.status(upstream.status).send('Upstream error');

  const cRange  = upstream.headers.get('content-range');
  const cLength = upstream.headers.get('content-length');

  res.status(upstream.status === 206 ? 206 : 200);
  res.setHeader('Content-Type',           'video/mp4');
  res.setHeader('Accept-Ranges',          'bytes');
  res.setHeader('Cache-Control',          'no-store, no-cache, private, must-revalidate');
  res.setHeader('Content-Disposition',    'inline');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Robots-Tag',           'noindex');
  if (cRange)  res.setHeader('Content-Range',  cRange);
  if (cLength) res.setHeader('Content-Length', cLength);
  res.removeHeader('ETag');
  res.removeHeader('Last-Modified');
  res.removeHeader('X-Powered-By');

  upstream.body.pipe(res as any);
  upstream.body.on('error', () => { try { res.end(); } catch {} });
}

// ─── handleChunk — fallback for browsers without SW support ─────────────────────
async function handleChunk(req: VercelRequest, res: VercelResponse) {
  const videoId = String(req.query.videoId || '');
  const idx     = parseInt(String(req.query.chunk || '0'), 10);
  const token   = (req.headers['x-chunk-token'] || req.query.chunkToken) as string | undefined;

  if (!token || !checkChunkToken(token, videoId, idx)) return res.status(403).send('Forbidden');
  if (badUA(req))      return res.status(403).send('Forbidden');
  if (badReferer(req)) return res.status(403).send('Forbidden');

  const vid = await getVid(videoId);
  if (!vid) return res.status(404).send('Not found');

  const start = idx * CONFIG.CHUNK_SIZE;
  const end   = start + CONFIG.CHUNK_SIZE - 1;
  const upH: Record<string, string> = {
    'User-Agent': 'Mozilla/5.0', Accept: '*/*',
    Range: `bytes=${start}-${end}`, Connection: 'keep-alive',
  };
  if (vid.isGoogleDrive) upH['Referer'] = 'https://drive.google.com/';

  const { default: fetch } = await import('node-fetch');
  const up = await (fetch as any)(vid.streamUrl, { headers: upH, redirect: 'follow', compress: false });
  if (up.status === 416) return res.status(204).send('');
  if (!up.ok && up.status !== 206) return res.status(up.status).send('Upstream error');

  const cRange = up.headers.get('content-range');
  const cLen   = up.headers.get('content-length');
  let isLast   = false;
  if (cRange) { const m = cRange.match(/bytes (\d+)-(\d+)\/(\d+)/); if (m) isLast = end >= parseInt(m[3], 10) - 1; }
  else if (up.status === 200) isLast = true;

  res.setHeader('Content-Type',           'video/mp4');
  res.setHeader('Cache-Control',          'no-store, no-cache, must-revalidate, private');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Content-Disposition',    'inline');
  res.setHeader('X-Next-Chunk-Token',     isLast ? '' : makeChunkToken(videoId, idx + 1));
  res.setHeader('X-Chunk-Index',          String(idx));
  res.setHeader('X-Is-Last-Chunk',        String(isLast));
  res.removeHeader('ETag'); res.removeHeader('Last-Modified'); res.removeHeader('X-Powered-By');
  if (cLen)   res.setHeader('Content-Length', cLen);
  if (cRange) res.setHeader('Content-Range',  cRange);
  res.status(206);
  up.body.pipe(res as any);
}

async function handleEmbed(req: VercelRequest, res: VercelResponse) {
  const videoId = String(req.query.videoId || '');
  const key     = (req.query.key || req.headers['x-security-string']) as string | undefined;
  if (!key || key.trim() !== CONFIG.MASTER_SECURITY_STRING.trim()) return res.status(403).send('Forbidden');
  const vid = await getVid(videoId);
  if (!vid) return res.status(404).send('Not found');
  const { default: fetch } = await import('node-fetch');
  const up = await (fetch as any)(vid.streamUrl, { headers: { 'User-Agent': 'Mozilla/5.0' } });
  if (!up.ok) return res.status(up.status).send('Embed error');
  res.setHeader('Content-Type', 'text/html');
  res.send(await up.text());
}

// ─── Main ────────────────────────────────────────────────────────────────────────
export default async function handler(req: VercelRequest, res: VercelResponse) {
  cors(req, res);
  if (req.method === 'OPTIONS') return res.status(204).end();
  try {
    if (req.method === 'POST') {
      if (req.body?.action === 'submit') return await handleSubmit(req, res);
      return res.status(400).json({ success: false, message: 'Unknown action' });
    }
    if (req.method === 'GET') {
      const a = String(req.query.action || 'health');
      if (a === 'play')    return await handlePlay(req, res);
      if (a === 'meta')    return await handleMeta(req, res);
      if (a === 'info')    return await handleInfo(req, res);
      if (a === 'chunk')   return await handleChunk(req, res);
      if (a === 'embed')   return await handleEmbed(req, res);
      if (a === 'health')  return res.status(200).json({ status: 'ok', ts: new Date().toISOString() });
      return res.status(400).json({ success: false, message: `Unknown action: ${a}` });
    }
    return res.status(405).json({ success: false, message: 'Method not allowed' });
  } catch (err: any) {
    console.error('[videoStream]', err);
    if (!res.headersSent) return res.status(500).json({ success: false, message: 'Internal server error' });
  }
}
